// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCwSW-c4v_Ew1pa8EBKiuRkaPNfYfNcFA',
    appId: '1:663050095577:web:aaeaef075d9eb9afb7a7c8',
    messagingSenderId: '663050095577',
    projectId: 'makanmate-6cfdb',
    authDomain: 'makanmate-6cfdb.firebaseapp.com',
    storageBucket: 'makanmate-6cfdb.firebasestorage.app',
    measurementId: 'G-6VBY80KMY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVeXSb9u3DT03QFs_MCOGHjowZzMmwQHI',
    appId: '1:663050095577:android:672b9d17170c4aaeb7a7c8',
    messagingSenderId: '663050095577',
    projectId: 'makanmate-6cfdb',
    storageBucket: 'makanmate-6cfdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaPrF8XXJdlGdxtNFtClB2ynaoz9XbHGQ',
    appId: '1:663050095577:ios:caeb1968418e6dbfb7a7c8',
    messagingSenderId: '663050095577',
    projectId: 'makanmate-6cfdb',
    storageBucket: 'makanmate-6cfdb.firebasestorage.app',
    iosBundleId: 'com.example.makanMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaPrF8XXJdlGdxtNFtClB2ynaoz9XbHGQ',
    appId: '1:663050095577:ios:caeb1968418e6dbfb7a7c8',
    messagingSenderId: '663050095577',
    projectId: 'makanmate-6cfdb',
    storageBucket: 'makanmate-6cfdb.firebasestorage.app',
    iosBundleId: 'com.example.makanMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCwSW-c4v_Ew1pa8EBKiuRkaPNfYfNcFA',
    appId: '1:663050095577:web:26a379f3627a91bab7a7c8',
    messagingSenderId: '663050095577',
    projectId: 'makanmate-6cfdb',
    authDomain: 'makanmate-6cfdb.firebaseapp.com',
    storageBucket: 'makanmate-6cfdb.firebasestorage.app',
    measurementId: 'G-FJ8EJGGX0X',
  );
}
